
- host: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: dotfiles | update .dotfiles
      tags: always
      copy:
        src: dotfiles/
        dest: ~/.dotfiles
        
  tasks:
    - starship.yml
    - tmux.yml
    - fonts.yml
