
- hosts: localhost
  connection: local
  vars_files: vars/main.yml
  tasks:
  
    - name: dotfiles | clone repo
      tags: always
      shell: "git clone {{ dotfiles_repo }} {{ dotfiles_dir }}"
    
    - import_tasks: tasks/git.yml 
    - import_tasks: tasks/starship.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/fonts.yml

    - name: dotfiles | stow | install
      package:
        name: stow
        state: present

    - name: dotfiles | stow | symlinks
      shell: sh scripts/run_stow.sh

