
- hosts: localhost
  connection: local
  vars_files: vars/main.yml
  tasks:
  
    - name: dotfiles | update .dotfiles
      tags: always
      copy:
        src: dotfiles/
        dest: ~/.dotfiles
    
    - import_tasks: tasks/git.yml 
    - import_tasks: tasks/starship.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/fonts.yml

    - name: eval | source bashrc
      shell: source ~/.bashrc
