# install and setup tmux

- name: tmux | install
  tags: setup,config,tmux,dotfiles
  become: true
  package:
    name: 
      - tmux
      - fzf
      - zoxide
    state: present

- name: tmux | clone plugins
  tags: setup,config, tmux, dotfiles
  block:
    - name: tmux | plugins | check dir
      stat:
        path: "~/.tmux/plugins/"
      register: plugins_dir

    - name: tmux | plugins | make dir
      file:
        path: "~/.tmux/plugins/"
        state: directory
      when: not plugins_dir.stat.exists

    - name: tmux | assert tpm dir
      stat:
        path: "~/.tmux/plugins/tpm"
      register: tpm_dir

    - name: tmux | clone tpm repo
      shell: "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
      when: not tpm_dir.stat.exists

- name: tmux | remove conf
  file:
    path: "{{ tmux.target }}"
    state: absent


